# -*- coding: utf-8 -*-
"""Copy of Matplotlib Interview Question

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkH43vx5Em9U1iiixSJVRo5Q54FWs431

# Problem:
Imagine you are working for a travel agency named "Wanderlust Adventures." Your team has been assigned a project to analyze and visualize the travel data for the past year. The data includes information about various destinations, the number of travelers per month, and the revenue generated. As the data analyst, you decide to use Matplotlib to create insightful visualizations. <br>
As a data analyst at "Wanderlust Adventures," you have been given a dataset containing monthly travel data for different destinations. The dataset includes information about the number of travelers and the revenue generated each month. Your task is to create three visualizations using Matplotlib: a line plot, a pie chart, and a scatter plot.

1.   <strong>Line Plot: </strong> Create a line plot using Matplotlib that illustrates the trend of both traveler count and revenue over the past year. The x-axis should represent the months, while the y-axis should represent the traveler count and revenue, respectively. The line plot should display two lines, one for traveler count and another for revenue, showcasing their trends over time.
2.   <strong>Pie Chart: </strong> Generate a pie chart using Matplotlib to display the distribution of traveler count among the top five destinations for the entire year. Each slice of the pie should represent a destination, and its size should correspond to the proportion of travelers visiting that particular destination.
3.  <strong>Scatter Plot: </strong> Create a scatter plot using Matplotlib that demonstrates the relationship between the number of travelers and the revenue generated for each month. Each data point on the scatter plot should represent a month, with the x-coordinate representing the traveler count and the y-coordinate representing the revenue generated.

<strong>Note:</strong> Use the file called "travel.csv"
"""

#Please use the file travel.csv for the above
#The dataset is available at https://tinyurl.com/travelDataset

import pandas as pd
import numpy as np

df = pd.read_csv('travel.csv')

df.head()

df_months = df.groupby('Month')['Travelers'].sum().reset_index(name = 'count_of_travellers')

df_months

df_revenue = df.groupby('Month')['Revenue'].sum().reset_index(name = 'revenue_each_month')
df_revenue

from matplotlib import pyplot as plt


df_months
plt.plot(df_months['Month'], df_months['count_of_travellers'], color = 'red')
plt.plot(df_revenue['Month'], df_revenue['revenue_each_month'], color = 'blue')
plt.xlabel("Months")
plt.ylabel("Count and Revenue")
plt.title("Count and Revenue generated by Travellers last year.")
plt.legend()
plt.show()

df_pie = df.groupby("Destination")['Travelers'].sum().reset_index(name = 'Travellers count')
df_result = df_pie.sort_values("Travellers count", ascending = False)

result = df_result[:5]
result

plt.pie(result['Travellers count'], labels=result['Destination'], autopct='%1.1f%%')

df_agg = df_months.merge(df_revenue, on = "Month")

plt.scatter(df_agg['count_of_travellers'], df_agg['revenue_each_month'], norm = 'linear')

plt.yscale('log')

for i in range(len(df_agg)):
    plt.text(df_agg['count_of_travellers'][i], df_agg['revenue_each_month'][i],
     (df_agg['count_of_travellers'][i], df_agg['revenue_each_month'][i], df_agg['Month'][i]), fontsize=10, ha='right')

plt.grid(True, which="both", ls="--")
plt.show()

import plotly.express as px
fig = px.scatter(df_agg,
                 x='count_of_travellers',
                 y='revenue_each_month',
                 hover_name='Month',  # Show month on hover
                 title='Traveler Count vs Revenue (Monthly)',
                 labels={'Traveler_Count': 'Number of Travelers', 'Revenue': 'Revenue Generated ($)'},
                 log_y=True)  # Apply log scale to y-axis

# Show the plot
fig.show()

